version: "2"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092
  login:
    build:
      context: ./API_login
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    volumes:
      - ./API_login/main.js:/app/main.js
    ports:
      - 3000:3000
  blocked:
    build:
      context: ./API_blocked
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 5000
      kafkaHost: kafka:9092
    volumes:
      - ./API_blocked/main.js:/app/main.js
      - ./API_blocked/db.json:/app/db.json
    ports:
      - 5000:5000